#!/usr/bin/env python3
"""
generate_content.py — Daily content generator for the GitHub streak bot.

Creates / appends to:
  1. log/YYYY-MM-DD.md   — a daily journal entry with a random dev quote
  2. README.md           — updates the "Streak Stats" block with today's count

Uses only the Python standard library (no pip install needed on Actions).
"""

from __future__ import annotations

import json
import os
import random
import re
import subprocess
import textwrap
from datetime import datetime, timezone
from pathlib import Path

# ─── Configuration ───────────────────────────────────────────────────────────

REPO_ROOT = Path(os.environ.get("GITHUB_WORKSPACE", Path(__file__).resolve().parent.parent))
LOG_DIR = REPO_ROOT / "log"
README = REPO_ROOT / "README.md"

# ─── Curated quotes (expand freely) ─────────────────────────────────────────

QUOTES: list[dict[str, str]] = [
    {"text": "First, solve the problem. Then, write the code.", "author": "John Johnson"},
    {"text": "Code is like humor. When you have to explain it, it's bad.", "author": "Cory House"},
    {"text": "Make it work, make it right, make it fast.", "author": "Kent Beck"},
    {"text": "Simplicity is prerequisite for reliability.", "author": "Edsger Dijkstra"},
    {"text": "Programs must be written for people to read.", "author": "Harold Abelson"},
    {"text": "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", "author": "Martin Fowler"},
    {"text": "The best error message is the one that never shows up.", "author": "Thomas Fuchs"},
    {"text": "Walking on water and developing software from a specification are easy if both are frozen.", "author": "Edward V. Berard"},
    {"text": "The most damaging phrase in the language is: 'We've always done it this way.'", "author": "Grace Hopper"},
    {"text": "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", "author": "Antoine de Saint-Exupéry"},
    {"text": "The function of good software is to make the complex appear to be simple.", "author": "Grady Booch"},
    {"text": "Before software can be reusable it first has to be usable.", "author": "Ralph Johnson"},
    {"text": "It's not a bug — it's an undocumented feature.", "author": "Anonymous"},
    {"text": "Talk is cheap. Show me the code.", "author": "Linus Torvalds"},
    {"text": "Truth can only be found in one place: the code.", "author": "Robert C. Martin"},
    {"text": "Java is to JavaScript what car is to carpet.", "author": "Chris Heilmann"},
    {"text": "Software and cathedrals are much the same — first we build them, then we pray.", "author": "Sam Redwine"},
    {"text": "In theory, there is no difference between theory and practice. But, in practice, there is.", "author": "Jan L. A. van de Snepscheut"},
    {"text": "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", "author": "Bill Gates"},
    {"text": "A language that doesn't affect the way you think about programming is not worth knowing.", "author": "Alan Perlis"},
]

# ─── Helpers ─────────────────────────────────────────────────────────────────


def _day_count() -> int:
    """Count the total number of daily-log files already in log/."""
    if not LOG_DIR.exists():
        return 0
    return sum(1 for f in LOG_DIR.glob("*.md") if f.name != "status.json")


def _streak_length() -> int:
    """
    Walk backwards from today counting consecutive days that have a log file.
    """
    from datetime import timedelta

    today = datetime.now(timezone.utc).date()
    streak = 0
    day = today
    while True:
        if (LOG_DIR / f"{day.isoformat()}.md").exists():
            streak += 1
            day -= timedelta(days=1)
        else:
            break
    # Include today's upcoming entry
    if streak == 0:
        streak = 1
    return streak


def _generate_daily_log(now: datetime) -> Path:
    """Create log/YYYY-MM-DD.md with a timestamped entry."""
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    date_str = now.strftime("%Y-%m-%d")
    log_file = LOG_DIR / f"{date_str}.md"

    quote = random.choice(QUOTES)
    day_number = _day_count() + 1

    entry = textwrap.dedent(f"""\
        # 📅 Daily Log — {date_str}

        | Field | Value |
        |-------|-------|
        | **Day #** | {day_number} |
        | **Timestamp (UTC)** | {now.strftime("%Y-%m-%d %H:%M:%S")} |
        | **Weekday** | {now.strftime("%A")} |

        ## 💡 Quote of the Day

        > *"{quote['text']}"*
        > — {quote['author']}

        ## 📝 Changelog

        - Auto-generated streak entry for day **{day_number}**.
        - Workflow trigger: `{os.environ.get("GITHUB_EVENT_NAME", "local")}`

        ---
        *Generated by [streak-bot](https://github.com/features/actions)*
    """)

    # Append if file already exists (e.g., manual re-run on the same day)
    mode = "a" if log_file.exists() else "w"
    if mode == "a":
        entry = "\n\n---\n\n" + f"## 🔄 Re-run at {now.strftime('%H:%M:%S')} UTC\n\n" + entry

    log_file.write_text(entry if mode == "w" else log_file.read_text() + entry, encoding="utf-8")
    print(f"✅ Wrote daily log → {log_file.relative_to(REPO_ROOT)}")
    return log_file


def _update_readme_stats(now: datetime, day_number: int) -> None:
    """
    Insert or update a <!-- STREAK-STATS --> block in README.md.
    If no README exists, create a minimal one.
    """
    streak = _streak_length()
    stats_block = textwrap.dedent(f"""\
        <!-- STREAK-STATS:START -->
        ## 📊 Streak Stats

        | Metric | Value |
        |--------|-------|
        | 🔥 Current streak | **{streak} day{"s" if streak != 1 else ""}** |
        | 📅 Total entries | **{day_number}** |
        | 🕐 Last updated | {now.strftime("%Y-%m-%d %H:%M UTC")} |
        <!-- STREAK-STATS:END -->""")

    if README.exists():
        content = README.read_text(encoding="utf-8")
        pattern = r"<!-- STREAK-STATS:START -->.*?<!-- STREAK-STATS:END -->"
        if re.search(pattern, content, re.DOTALL):
            content = re.sub(pattern, stats_block, content, flags=re.DOTALL)
        else:
            content += "\n\n" + stats_block + "\n"
    else:
        content = textwrap.dedent(f"""\
            # 🔥 GitHub Streak Bot

            Automated daily commits to maintain a contribution streak.

            {stats_block}
        """)

    README.write_text(content, encoding="utf-8")
    print(f"✅ Updated README stats block")


# ─── Main ────────────────────────────────────────────────────────────────────

def main() -> None:
    now = datetime.now(timezone.utc)
    print(f"🕐 Current UTC time: {now.isoformat()}")

    _generate_daily_log(now)
    day_number = _day_count()
    _update_readme_stats(now, day_number)

    print(f"🎯 Day #{day_number} content generated successfully.")


if __name__ == "__main__":
    main()
